[build]
command = "yarn build"
publish = "dist"


[dev]
command = "yarn dev"

[[redirects]]
force = false
from = "/*"
status = 200
to = "/index.html"

[[edge_functions]]
path = "/.netlify/functions/dropbox-proxy"
function = "fetch-dropbox-data"